services:
    aslams-app:
        build: .
        ports:
            - '4001:4000'
        env_file:
            - /opt/aslams-backend/.env
        environment:
            - NODE_ENV=production
            - PORT=4000
        volumes:
            - ./uploads:/app/uploads
        restart: unless-stopped
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--quiet',
                    '--tries=1',
                    '--spider',
                    'http://localhost:4000/api/health',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        container_name: aslams-backend
        networks:
            - app-network

networks:
    app-network:
        external: true
